"""DB models fixes

Revision ID: 02cab5ea1419
Revises: b34f663870d4
Create Date: 2023-05-14 19:58:42.376814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02cab5ea1419'
down_revision = 'b34f663870d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('correlation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correlation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('target_user_id', sa.INTEGER(), nullable=False),
    sa.Column('another_user_id', sa.INTEGER(), nullable=False),
    sa.Column('correlation', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['target_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
