"""DB models fixes

Revision ID: b34f663870d4
Revises: 668a568bd16b
Create Date: 2023-05-13 20:48:13.838256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'b34f663870d4'
down_revision = '668a568bd16b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('correlation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('another_user_id', sa.Integer(), nullable=False),
    sa.Column('correlation', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['target_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('comments')
        batch_op.drop_column('ratings')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('correlations')
        batch_op.drop_column('ratings')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ratings', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('correlations', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ratings', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('comments', sqlite.JSON(), nullable=True))

    op.drop_table('rating')
    op.drop_table('correlation')
    op.drop_table('comment')
    # ### end Alembic commands ###
